frogfish_bigthink:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: bigthink
      dataset: dev
      threads: 4  
      OPTIONAL_CONFIG: VALUE

    prod:
      type: bigquery
      method: oauth
      project: bigthink
      dataset: prod
      threads: 4  
      OPTIONAL_CONFIG: VALUE

  target: dev