select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,     
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    1 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Open - Not Contacted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    1 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Closed - Not Converted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    1 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'New'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    1 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Do Not Contact'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    1 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Defaulted Merchant'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    1 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - DNQ'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    1 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty Submitted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    1 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Funded - In Repayment'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    1 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Defaulted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    1 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Offers In'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    1 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = '3rd Attempt'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    1 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Open'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    1 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Closed - Lost'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    1 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty Prospect'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    1 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - Unresponsive'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    1 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty Funders Declined'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    1 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Working - Application Out'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    1 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Working - Contacted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    1 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'FBIG Startup'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    1 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - App Out'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    1 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Opportunity'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,   
    utm_term,
    lead_created_date,
    utm_source,     
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    1 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - DNQ Future'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    1 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - In Contact'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    1 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty Pending Additional Info'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    1 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Funders Declined'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source, 
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    1 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty Declined'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    1 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Hot Lead'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    1 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Closed - Converted'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    1 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Pending Additional INFO'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    1 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,   
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    1 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Submitted to Funders'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    1 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Closed - Won'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    1 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Specialty - App In Collecting Docs'

union all

select distinct
    lead_id as id,
    lead_stage_date as date,
    lead_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    1 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    1 as is_lead,
    0 as is_opportunity
from {{ ref('fct_sf_leads') }}
where lead_stage = 'Merchant Reviewing Offers'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    1 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Declined'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    1 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Contracts Out'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    1 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Ready to Order Contracts'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    1 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Referred'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    1 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Closed'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    1 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Sent to Operations'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
        0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    1 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Application In'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    1 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Renewal Prospecting'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    1 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Contracts In'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,   
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    1 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Application Missing Info'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    1 as approved,
    0 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Approved'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    1 as underwriting,
    0 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Underwriting'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,
    gclid,
    funded_amount,
    commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    1 as funded,
    0 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Funded'

union all

select distinct
    opportunity_id as id,
    opportunity_stage_change_date as date,
    opportunity_stage as stage,
    utm_campaign,
    utm_term,
    lead_created_date,
    utm_source,
    utm_medium,
    utm_content,
    lead_source,
    iso_name,   
    gclid,
    0 as funded_amount,
    0 as commission,
    0 as `open_not_contacted`,
    0 as `closed_not_converted`,
    0 as `new`,
    0 as do_not_contact,
    0 as `defaulted_merchant`,
    0 as specialty_dnq,
    0 as specialty_submitted,
    0 as funded_in_repayment,
    0 as `defaulted`,
    0 as offers_in,
    0 as third_attempt,
    0 as `open`,
    0 as `closed_lost`,
    0 as specialty_prospect,
    0 as specialty_unresponsive,
    0 as specialty_funders_declined,
    0 as working_application_out,
    0 as working_contacted,
    0 as fbig_startup,
    0 as specialty_app_out,
    0 as opportunity,
    0 as specialty_dnq_future,
    0 as specialty_in_contact,
    0 as specialty_pending_additional_info,
    0 as funders_declined,
    0 as specialty_declined,
    0 as hot_lead,
    0 as `closed_converted`,
    0 as pending_additional_info,
    0 as specialty,
    0 as submitted_to_funders,
    0 as `closed_won`,
    0 as specialty_app_in_collecting_docs,
    0 as merchant_reviewing_offers,
    0 as declined,
    0 as contracts_out,
    0 as ready_to_order_contracts,
    0 as referred,
    0 as `closed`,
    0 as sent_to_operations,
    0 as application_in,
    0 as `renewal_prospecting`,
    0 as contracts_in,
    0 as application_missing_info,
    0 as approved,
    0 as underwriting,
    0 as funded,
    1 as pitched,
    0 as is_lead,
    1 as is_opportunity
from {{ ref('fct_sf_opportunities_stage') }}
where opportunity_stage = 'Pitched'