version: 2

sources:
  - name: Google_Ads  # Logical name for the source
    database: bigthink  # BigQuery project ID
    schema: Google_Ads  # BigQuery dataset
    tables:
      - name: account_performance_report # name you want to call it
        identifier: account_performance_report # name for the source table
        description: "Contains data about Google Ads source synced from Airbyte."

  - name: Salesforce  # Logical name for the source
    database: bigthink  # BigQuery project ID
    schema: Salesforce  # BigQuery dataset
    tables:
      - name: Account
        identifier: Account
        description: "Contains data about ** source synced from Connector Name."
      - name: Contact
        identifier: Contact
        description: "Contains data about ** source synced from Connector Name."
      - name: Lead
        identifier: Lead
        description: "Contains data about ** source synced from Connector Name."
      - name: LeadHistory
        identifier: LeadHistory
        description: "Contains data about ** source synced from Connector Name."
      - name: OpportunityHistory
        identifier: OpportunityHistory
        description: "Contains data about ** source synced from Connector Name."
      - name: Opportunity
        identifier: Opportunity
        description: "Contains data about ** source synced from Connector Name."
      - name: OpportunityStage
        identifier: OpportunityStage
        description: "Contains data about ** source synced from Connector Name."
      - name: Task
        identifier: Task
        description: "Contains data about ** source synced from Connector Name."
  - name: Google_Ads  # Logical name for the source
    database: bigthink  # BigQuery project ID
    schema: Google_Ads  # BigQuery dataset
    tables:
      - name: campaign
        identifier: campaign
        description: "Contains data about GoogleAds source synced."