version: 2

sources:
  - name: Google_Ads  # Logical name for the source
    database: bigthink  # BigQuery project ID
    schema: Google_Ads  # BigQuery dataset
    tables:
      - name: account_performance_report # name you want to call it
        identifier: account_performance_report # name for the source table
        description: "Contains data about Google Ads source synced from Airbyte."

  - name: Salesforce  # Logical name for the source
    database: bigthink  # BigQuery project ID
    schema: Salesforce  # BigQuery dataset
    tables:
      - name: Account
        identifier: Account
        description: "Contains data about ** source synced from Connector Name."